service: api-workroom
runtime: python39
entrypoint: gunicorn -b :$PORT app.main:app

handlers:
- url: /.*
  script: auto
  
vpc_access_connector:
 name: projects/hip-arcadia-419017/locations/us-central1/connectors/workroom-alloydb