service: api-workroom
runtime: python39
entrypoint: uvicorn app.main:app --host=0.0.0.0 --port=${PORT} --log-level=info

handlers:
- url: /.*
  script: auto
  
vpc_access_connector:
 name: projects/hip-arcadia-419017/locations/us-central1/connectors/workroom-alloydb
  